---
- hosts: masters
  tasks:
    - block:
      - name: Change the ClientID and ClientSecret in master-config.yaml
        replace:
          dest: /etc/origin/master/master-config.yaml
          regexp: '{{ item.reg_conf_var }}.*'
          replace: '{{ item.reg_conf_var }}: {{ item.reg_fact_val }}'
          backup: yes
        with_items:
          - reg_conf_var: clientID
            reg_fact_val: "{{ clientID }}"
          - reg_conf_var: clientSecret
            reg_fact_val: "{{ clientSecret }}"
  
      - name: restart master api
        service: name=atomic-openshift-master-api state=restarted
    
      when: clientID is defined and clientID != ''

- hosts: OSEv3
  name: 
  tasks:
    - name: Config default hours for ec2 instances 
      lineinfile:
        dest: /etc/charlie.conf 
        regexp: ^HOURS=6
        line: HOURS={{ HOURS }}
      when: HOURS is defined HOURS != ''
